export const laboratoryKinds = [
  "actions",
  "cayley",
  "characters",
  "coloring",
  "conjugation",
  "cosets",
  "cube",
  "cyclic-eigenvalues",
  "diagram",
  "field",
  "finite-matrices",
  "homomorphism",
  "linear-quotient",
  "module",
  "orthogonal",
  "permutation",
  "polygon",
  "polynomial",
  "product",
  "quadratic-integers",
  "quadratic-quotient",
  "representation",
  "ring",
  "semidirect",
  "square-modes",
  "subgroups",
  "sylow",
] as const;
export type LaboratoryKind = (typeof laboratoryKinds)[number];
