export const learningRoutes = [
  {
    id: "actions",
    title: "Groups → actions → representations",
    description:
      "Start with operations, count an orbit, then turn permutations into linear maps.",
    lessons: [
      "foundations-functions",
      "mh2220-axioms",
      "mh2220-inverse-order",
      "mh2220-subgroups",
      "mh2220-permutations",
      "mh2220-homomorphism",
      "mh2220-cosets",
      "mh2220-actions",
      "mh2220-orbit-stabilizer",
      "mh2220-normal",
      "mh2220-quotient",
      "mh2220-first-isomorphism",
      "cube-four-actions",
      "foundations-linear-algebra",
      "mh2220-permutation-matrices",
      "ureca-linear-action",
      "ureca-permutation-module",
      "ureca-invariant-subspaces",
      "representations-real-complex",
      "representations-maschke",
      "ureca-intertwiners",
      "odyssey-schur",
      "odyssey-character-table",
    ],
  },
  {
    id: "rings",
    title: "Arithmetic → rings → fields",
    description:
      "Follow units, ideals and quotient arithmetic before adjoining roots.",
    lessons: [
      "mh2220-congruence",
      "m3220-rings",
      "m3220-units",
      "m3220-domains",
      "m3220-ring-hom",
      "m3220-ideals",
      "m3220-quotient-ring",
      "m3220-crt",
      "m3220-polynomial",
      "m3220-polynomial-division",
      "m3220-irreducibility-tests",
      "m3220-algebraic",
      "m3220-finite-field-four",
      "quadratic-quotient",
    ],
  },
  {
    id: "modules",
    title: "Modules → structure",
    description:
      "Begin with scalar actions and quotients; later entries are advanced proof sketches.",
    lessons: [
      "m3220-modules",
      "m3220-submodules",
      "modules-generators",
      "m3220-annihilator",
      "ureca-group-algebra",
      "tensor-products",
      "m3220-module-chains",
      "m3220-noetherian",
      "m3220-jacobson",
      "m3220-nakayama",
      "m3220-artinian",
      "algebra-wedderburn",
      "algebra-radical",
    ],
  },
];
