"use client";
import { useState } from "react";
import type { Lesson } from "@/lib/algebra/engine";
import { Math as M } from "./Math";
import {
  leftCyclicModule,
  rightCyclicModule,
  tensorPresentation,
} from "@/lib/algebra/tensor-balancing";

export function TensorBalancingLab({ lesson }: { lesson: Lesson }) {
  const [rightModulus, setRightModulus] = useState(2);
  const [leftModulus, setLeftModulus] = useState(4);
  const [scalar, setScalar] = useState(3);
  const [u, setU] = useState(1);
  const [v, setV] = useState(1);
  const [prediction, setPrediction] = useState("");
  const [revealed, setRevealed] = useState(false);
  const [failure, setFailure] = useState(false);
  const model = tensorPresentation(
    rightCyclicModule(rightModulus),
    leftCyclicModule(leftModulus),
    scalar,
    u,
    v,
  );
  const reset = () => {
    setPrediction("");
    setRevealed(false);
    setFailure(false);
  };
  return (
    <div className="foundation-lab">
      <p>
        What does the balancing relation identify? U=ℤ/mℤ is a right ℤ-module,
        V=ℤ/nℤ is a left ℤ-module. Their tensor product is an abelian group
        generated by t=[1]⊗[1], with relations mt=0 and nt=0. The right/left
        order matters for a noncommutative base ring.
      </p>
      <M block>
        {
          "(ur)\\otimes v=u\\otimes(rv),\\qquad (\\mathbb Z/m)\\otimes_{\\mathbb Z}(\\mathbb Z/n)\\cong\\mathbb Z/\\gcd(m,n)"
        }
      </M>
      <div className="lab-controls">
        <label>
          Right module U=ℤ/mℤ; choose m
          <select
            value={rightModulus}
            onChange={(e) => {
              setRightModulus(Number(e.target.value));
              setU(0);
              reset();
            }}
          >
            {[2, 3, 4, 6, 8, 12].map((m) => (
              <option key={m} value={m}>
                {m}
              </option>
            ))}
          </select>
        </label>
        <label>
          Left module V=ℤ/nℤ; choose n
          <select
            value={leftModulus}
            onChange={(e) => {
              setLeftModulus(Number(e.target.value));
              setV(0);
              reset();
            }}
          >
            {[2, 3, 4, 6, 8, 12].map((n) => (
              <option key={n} value={n}>
                {n}
              </option>
            ))}
          </select>
        </label>
        <label>
          Integer scalar r
          <select
            value={scalar}
            onChange={(e) => {
              setScalar(Number(e.target.value));
              reset();
            }}
          >
            {[0, 1, 2, 3, 4, 6].map((r) => (
              <option key={r} value={r}>
                {r}
              </option>
            ))}
          </select>
        </label>
        <label>
          Right-module vector [u]
          <select
            value={u}
            onChange={(e) => {
              setU(Number(e.target.value));
              reset();
            }}
          >
            {Array.from({ length: rightModulus }, (_, index) => (
              <option key={index} value={index}>
                [{index}]
              </option>
            ))}
          </select>
        </label>
        <label>
          Left-module vector [v]
          <select
            value={v}
            onChange={(e) => {
              setV(Number(e.target.value));
              reset();
            }}
          >
            {Array.from({ length: leftModulus }, (_, index) => (
              <option key={index} value={index}>
                [{index}]
              </option>
            ))}
          </select>
        </label>
      </div>
      <label className="prediction-prompt">
        Predict the order of t and compare (ur)⊗v with u⊗(rv) before revealing.
        <textarea
          value={prediction}
          onChange={(e) => setPrediction(e.target.value)}
          aria-label="Your mathematical prediction"
        />
      </label>
      <button
        type="button"
        disabled={!prediction.trim()}
        onClick={() => setRevealed(true)}
      >
        Test my prediction
      </button>
      {revealed && (
        <div className="live-mathematics" aria-live="polite">
          <h3>Balanced generator and relation evidence</h3>
          <p>
            Relations {rightModulus}t=0 and {leftModulus}t=0 give ord(t)=gcd(
            {rightModulus},{leftModulus})={model.gcd}. Thus U⊗_ℤV≅ℤ/{model.gcd}ℤ
            with elements {`{${model.tensorElements.join(", ")}}`}.
          </p>
          <p>
            ([{u}]·{scalar})⊗[{v}]=[{model.leftRepresentative}]⊗[{v}]=
            {model.leftValue}t; [{u}]⊗({scalar}·[{v}])=[{u}]⊗[
            {model.rightRepresentative}]={model.rightValue}t. Balance:{" "}
            {model.balanced ? "equal" : "unequal"}. The pure tensor [{u}]⊗[{v}]=
            {model.pureValue}t.
          </p>
          <p>
            {model.nonPureExample}. {model.dualHomExample}.
          </p>
          {failure && (
            <p role="status">
              Failure witness: ℤ/2⊗_ℤℤ/3=0 because 2t=3t=0 forces t=0. Two
              nonzero factors need not yield a nonzero tensor product.
            </p>
          )}
          <table>
            <caption>Typed balancing and cyclic tensor relation</caption>
            <thead>
              <tr>
                <th scope="col">Check</th>
                <th scope="col">Value</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row">Right input</th>
                <td>
                  ℤ/{rightModulus}ℤ, u=[{u}]
                </td>
              </tr>
              <tr>
                <th scope="row">Left input</th>
                <td>
                  ℤ/{leftModulus}ℤ, v=[{v}]
                </td>
              </tr>
              <tr>
                <th scope="row">Generator order</th>
                <td>{model.generatorOrder}</td>
              </tr>
              <tr>
                <th scope="row">(ur)⊗v</th>
                <td>{model.leftValue}t</td>
              </tr>
              <tr>
                <th scope="row">u⊗(rv)</th>
                <td>{model.rightValue}t</td>
              </tr>
            </tbody>
          </table>
        </div>
      )}
      <button
        type="button"
        onClick={() => {
          setRightModulus(2);
          setLeftModulus(3);
          setU(1);
          setV(1);
          setScalar(1);
          setPrediction("The generator may vanish despite nonzero factors.");
          setRevealed(true);
          setFailure(true);
        }}
      >
        Try the zero tensor-product failure
      </button>
      <div className="laboratory-debrief">
        <h3>Theorem debrief and proof boundary</h3>
        <p>
          The cyclic presentation is a worked ℤ-module computation. For a right
          R-module U and left R-module V, the universal property says every
          balanced biadditive map U×V→A to an abelian group factors uniquely
          through U⊗_R V. The finite table illustrates that property; it does
          not prove it for arbitrary R. An external product π⊠ρ of G- and
          H-representations uses the underlying field tensor with a separate
          (G×H)-action; its notation and kernel question are distinct.
        </p>
        <p>{lesson.title} keeps the module sides explicit.</p>
      </div>
    </div>
  );
}
